;
; Convert ATD -> Swift 
;
(rule
  (targets
    allcaps.swift
    everything.swift
  )
  (deps
    ../atd-input/ALLCAPS.atd
    ../atd-input/everything.atd
  )
  (action
    (run %{bin:atdswift} %{deps})))

;
; Typecheck and run the tests on the generated Swift code.
;
(rule
 (alias runtest)
 (package atdswift)
 (deps
  everything.swift
  (glob_files *.swift))
 (action
  (progn
   (run swift -version))))
