/** Generated by atdswift from type definitions in everything.atd.

This implements structs for the types defined in 'everything.atd', providing
methods and functions to convert data from/to JSON.
*/
import Foundation

// Public classes



// This was inserted by the user.
import SwiftUI


struct RecursiveClass: Codable {
    // Original type: recursive_class = { ... }

    var id: Int
    var flag: Bool
    var children: [RecursiveClass]

    static func fromJson(json: Data) throws -> RecursiveClass {
        return try JSONDecoder().decode(RecursiveClass.self, from: json)
    }

    func toJson() throws -> Data {
        return try JSONEncoder().encode(self)
    }

    static func fromJsonString(jsonString: String) throws -> RecursiveClass {
        let jsonData = jsonString.data(using: .utf8)!
        return try JSONDecoder().decode(RecursiveClass.self, from: jsonData)
    }

    func toJsonString() throws -> String {
        let jsonData = try JSONEncoder().encode(self)
        return String(data: jsonData, encoding: .utf8)!
    }
}


class Root_:
    """Original type: kind = [ ... | Root | ... ]"""

    @property
    def kind(self) -> str:
        """Name of the class representing this variant."""
        return 'Root_'

    @staticmethod
    def to_json() -> Any:
        return 'Root'

    def to_json_string(self, **kw: Any) -> str:
        return json.dumps(self.to_json(), **kw)


class Thing:
    """Original type: kind = [ ... | Thing of ... | ... ]"""

    value: Int

    @property
    def kind(self) -> str:
        """Name of the class representing this variant."""
        return 'Thing'

    def to_json(self) -> Any:
        return ['Thing', _atd_write_int(self.value)]

    def to_json_string(self, **kw: Any) -> str:
        return json.dumps(self.to_json(), **kw)


class WOW:
    """Original type: kind = [ ... | WOW | ... ]"""

    @property
    def kind(self) -> str:
        """Name of the class representing this variant."""
        return 'WOW'

    @staticmethod
    def to_json() -> Any:
        return 'wow'

    def to_json_string(self, **kw: Any) -> str:
        return json.dumps(self.to_json(), **kw)


class Amaze:
    """Original type: kind = [ ... | Amaze of ... | ... ]"""

    value: [String]

    @property
    def kind(self) -> str:
        """Name of the class representing this variant."""
        return 'Amaze'

    def to_json(self) -> Any:
        return ['!!!', _atd_write_list(_atd_write_string)(self.value)]

    def to_json_string(self, **kw: Any) -> str:
        return json.dumps(self.to_json(), **kw)


class Kind:
    """Original type: kind = [ ... ]"""

    value: Union[Root_, Thing, WOW, Amaze]

    @property
    def kind(self) -> str:
        """Name of the class representing this variant."""
        return self.value.kind

    @classmethod
    def from_json(cls, x: Any) -> 'Kind':
        if isinstance(x, str):
            if x == 'Root':
                return cls(Root_())
            if x == 'wow':
                return cls(WOW())
            _atd_bad_json('Kind', x)
        if isinstance(x, List) and len(x) == 2:
            cons = x[0]
            if cons == 'Thing':
                return cls(Thing(_atd_read_int(x[1])))
            if cons == '!!!':
                return cls(Amaze(_atd_read_list(_atd_read_string)(x[1])))
            _atd_bad_json('Kind', x)
        _atd_bad_json('Kind', x)

    def to_json(self) -> Any:
        return self.value.to_json()

    @classmethod
    def from_json_string(cls, x: str) -> 'Kind':
        return cls.from_json(json.loads(x))

    def to_json_string(self, **kw: Any) -> str:
        return json.dumps(self.to_json(), **kw)


class Alias:
    """Original type: alias"""

    value: [Int]

    @classmethod
    def from_json(cls, x: Any) -> 'Alias':
        return cls(_atd_read_list(_atd_read_int)(x))

    def to_json(self) -> Any:
        return _atd_write_list(_atd_write_int)(self.value)

    @classmethod
    def from_json_string(cls, x: str) -> 'Alias':
        return cls.from_json(json.loads(x))

    def to_json_string(self, **kw: Any) -> str:
        return json.dumps(self.to_json(), **kw)


class KindParametrizedTuple:
    """Original type: _kind_parametrized_tuple"""

    value: (Kind, Kind, Int)

    @classmethod
    def from_json(cls, x: Any) -> 'KindParametrizedTuple':
        return cls((lambda x: (Kind.from_json(x[0]), Kind.from_json(x[1]), _atd_read_int(x[2])) if isinstance(x, list) and len(x) == 3 else _atd_bad_json('array of length 3', x))(x))

    def to_json(self) -> Any:
        return (lambda x: [(lambda x: x.to_json())(x[0]), (lambda x: x.to_json())(x[1]), _atd_write_int(x[2])] if isinstance(x, tuple) and len(x) == 3 else _atd_bad_python('tuple of length 3', x))(self.value)

    @classmethod
    def from_json_string(cls, x: str) -> 'KindParametrizedTuple':
        return cls.from_json(json.loads(x))

    def to_json_string(self, **kw: Any) -> str:
        return json.dumps(self.to_json(), **kw)


struct IntFloatParametrizedRecord: Codable {
    // Original type: _int_float_parametrized_record = { ... }

    var field_a: Int
    var field_b: [Double] = []

    static func fromJson(json: Data) throws -> IntFloatParametrizedRecord {
        return try JSONDecoder().decode(IntFloatParametrizedRecord.self, from: json)
    }

    func toJson() throws -> Data {
        return try JSONEncoder().encode(self)
    }

    static func fromJsonString(jsonString: String) throws -> IntFloatParametrizedRecord {
        let jsonData = jsonString.data(using: .utf8)!
        return try JSONDecoder().decode(IntFloatParametrizedRecord.self, from: jsonData)
    }

    func toJsonString() throws -> String {
        let jsonData = try JSONEncoder().encode(self)
        return String(data: jsonData, encoding: .utf8)!
    }
}


struct Root: Codable {
    // Original type: root = { ... }

    var id: String
    var await_: Bool
    var x___init__: Double
    var items: [[Int]]
    var aliased: Alias
    var point: (Double, Double)
    var kinds: [Kind]
    var assoc1: [(Double, Int)]
    var assoc2: [(String, Int)]
    var assoc3: [Double: Int]
    var assoc4: [String: Int]
    var nullables: [Int?]
    var options: [Int?]
    var untyped_things: [Data]
    var parametrized_record: IntFloatParametrizedRecord
    var parametrized_tuple: KindParametrizedTuple
    var maybe: Int?
    var extras: [Int] = []
    var answer: Int = 42

    static func fromJson(json: Data) throws -> Root {
        return try JSONDecoder().decode(Root.self, from: json)
    }

    func toJson() throws -> Data {
        return try JSONEncoder().encode(self)
    }

    static func fromJsonString(jsonString: String) throws -> Root {
        let jsonData = jsonString.data(using: .utf8)!
        return try JSONDecoder().decode(Root.self, from: jsonData)
    }

    func toJsonString() throws -> String {
        let jsonData = try JSONEncoder().encode(self)
        return String(data: jsonData, encoding: .utf8)!
    }
}


class Pair:
    """Original type: pair"""

    value: (String, Int)

    @classmethod
    def from_json(cls, x: Any) -> 'Pair':
        return cls((lambda x: (_atd_read_string(x[0]), _atd_read_int(x[1])) if isinstance(x, list) and len(x) == 2 else _atd_bad_json('array of length 2', x))(x))

    def to_json(self) -> Any:
        return (lambda x: [_atd_write_string(x[0]), _atd_write_int(x[1])] if isinstance(x, tuple) and len(x) == 2 else _atd_bad_python('tuple of length 2', x))(self.value)

    @classmethod
    def from_json_string(cls, x: str) -> 'Pair':
        return cls.from_json(json.loads(x))

    def to_json_string(self, **kw: Any) -> str:
        return json.dumps(self.to_json(), **kw)


struct DefaultList: Codable {
    // Original type: default_list = { ... }

    var items: [Int] = []

    static func fromJson(json: Data) throws -> DefaultList {
        return try JSONDecoder().decode(DefaultList.self, from: json)
    }

    func toJson() throws -> Data {
        return try JSONEncoder().encode(self)
    }

    static func fromJsonString(jsonString: String) throws -> DefaultList {
        let jsonData = jsonString.data(using: .utf8)!
        return try JSONDecoder().decode(DefaultList.self, from: jsonData)
    }

    func toJsonString() throws -> String {
        let jsonData = try JSONEncoder().encode(self)
        return String(data: jsonData, encoding: .utf8)!
    }
}
