;
; We test in two phases:
;
; 1. Check that the generated Swift code is what we expect.
;

(rule
 (alias runtest)
 (package atdswift)
 (action
   (diff swift-expected/everything.swift
     swift-tests/everything.swift)))

; 2. Run the generated Python code and check that is reads or writes JSON
;    data as expected.
;
; See swift-tests/dune
